import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
  faFutbol,
  faClock,
  faCalendarCheck,
  faUser,
  faChevronLeft,
  faBars,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faPhone,
  faRightFromBracket,
  faGear,
  faArrowLeft,
  faPlus,
  faPenToSquare,
  faTrash,
  faArrowUpFromBracket,
  faChartLine,
  faDollarSign,
  faBolt,
  faGaugeHigh,
  faCircleCheck,
  faCircleXmark,
  faHourglassHalf,
  faClockRotateLeft,
  faBell,
  faUsers,
  faCompass,
  
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faFutbol,
  faClock,
  faCalendarCheck,
  faUser,
  faChevronLeft,
  faBars,
  faEnvelope,
  faLock,
  faEye,
  faEyeSlash,
  faPhone,
  faRightFromBracket,
  faGear,
  faArrowLeft,
  faPlus,
  faPenToSquare,
  faTrash,
  faArrowUpFromBracket,
  faChartLine,
  faDollarSign,
  faBolt,
  faGaugeHigh,
  faCircleCheck,
  faCircleXmark,
  faHourglassHalf,
  faClockRotateLeft,
  faBell,
  faBolt,
  faUsers,
  faCompass
);

export default FontAwesomeIcon;
