# Generated by Django 5.2.1 on 2025-06-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soccerfield',
            old_name='field_image',
            new_name='image',
        ),
    ]
