# Generated by Django 5.2.1 on 2025-06-22 02:27

import cancha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancha', '0002_rename_field_image_soccerfield_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerfield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cancha.models.custom_field_image_upload),
        ),
    ]
