# Generated by Django 5.2.1 on 2025-05-28 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cancha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('motivo_bloqueo', models.TextField(blank=True, null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cancha.soccerfield')),
            ],
        ),
    ]
