# Generated by Django 5.2.1 on 2025-06-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cancha', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFlexible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recurrente', 'Recurrente semanal'), ('excepcion', 'Excepción por fecha')], default='recurrente', max_length=20)),
                ('diaSemana', models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('horaInicio', models.TimeField(blank=True, null=True)),
                ('horaFin', models.TimeField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('motivo_bloqueo', models.TextField(blank=True, null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_flexibles', to='cancha.soccerfield')),
            ],
        ),
    ]
