# Generated by Django 5.2.1 on 2025-06-10 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancha', '0002_rename_field_image_soccerfield_image'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_exceptions', to='cancha.soccerfield')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('cancha', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('cerrado', models.BooleanField(default=False)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='cancha.soccerfield')),
            ],
            options={
                'ordering': ['dia'],
                'unique_together': {('cancha', 'dia')},
            },
        ),
        migrations.DeleteModel(
            name='HorarioFlexible',
        ),
    ]
