# Generated by Django 5.2.1 on 2025-06-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_dateexception_weeklyschedule_delete_horarioflexible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='cerrado',
        ),
    ]
