# Generated by Django 5.2.1 on 2025-07-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_remove_weeklyschedule_cerrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateexception',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
